Website = "https://github.com/eliasthecactus/webator"
Email    = "mail@elias.uno"

[Details]
  Icon  = "icon.png"
  Name  = "Webator"
  ID    = "ch.eliasthecactus.webator"
  Version = "1.3.6"
  Build = 1
